applications/api/urls.py
from django.urls import path

from . import views


app_name = 'api'
urlpatterns = [
    # Demonstration of API
    path(f'test/excel', views.Test_Table.as_view(), name='test_excel'),
    path(f'test/json', views.Test_FactGenerator.as_view(), name='test_json'),
]

applications/content/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'content'
urlpatterns = [
    path('docs/', views.Docs, name='docs'),
    path('python/django/', views.ContentPage_Django, name='django'),
    path('javascript/react/', views.ContentPage_React, name='react'),
]

applications/website/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'website'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    # React Frontend Examples
    path('react/app/', views.Example_React_App, name='react_app'),
    path('react/component/', views.Example_React_Component, name='react_component'),
]

configuration/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from applications.website.SiteMap import SiteMap
sitemaps = {'site': SiteMap()}

urlpatterns = [
    # Other Urls
    path('admin/', admin.site.urls), # Admin Panel
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # Site Map
    # Website Page Urls
    path('', include('applications.website.urls')), # Landing Page
    path('content/', include('applications.content.urls')), # CMS
    # Application Page Urls
        # Restful API
    path('api-auth/', include('rest_framework.urls')), # API | https://www.django-rest-framework.org/#installation
    path('data/api/', include('applications.api.urls')), # API | Restful API
]

applications/api/na/models.py
from django.db import models

# Create your models here.

applications/content/na/models.py
from django.db import models

# Create your models here.

applications/website/na/models.py
from django.db import models

# Create your models here.

applications/api/views.py
from django.shortcuts import render
import pandas as pd
from rest_framework.views import APIView
from rest_framework.response import Response


class Test_Table(APIView):
    '''Demonstration of API 01'''
    def get(self, request):
        self.data = pd.read_excel(f'./static/database/data.xlsx').fillna(value='null')
        return Response(self.data.to_dict(orient='records'))


class Test_FactGenerator(APIView):
    '''Demonstration of API 02'''
    def get(self, request):
        self.data = pd.read_json(f'./static/database/FactGenerator.json')
        return Response(self.data.to_dict(orient='records'))

applications/content/views.py
import os
from django.shortcuts import render
import markdown


def Docs(request):
    # Read the Markdown file
    markdown_file = os.path.join('ReadMe.md')
    with open(markdown_file, 'r') as file:
        markdown_text = file.read()
    # Convert the Markdown text to HTML
    content = markdown.markdown(markdown_text)
    # Render the HTML in the template
    return render(request, 'applications/content/docs.html', {'content': content})


def ContentPage_Django(request):
    # Read the Markdown file
    markdown_file = os.path.join(os.path.dirname(__file__), 'cms', 'article_django.md')
    with open(markdown_file, 'r') as file:
        markdown_text = file.read()
    # Convert the Markdown text to HTML
    content = markdown.markdown(markdown_text)
    # Render the HTML in the template
    return render(request, 'applications/content/content_django.html', {'content': content})


def ContentPage_React(request):
    # Read the Markdown file
    markdown_file = os.path.join(os.path.dirname(__file__), 'cms', 'article_react.md')
    with open(markdown_file, 'r') as file:
        markdown_text = file.read()
    # Convert the Markdown text to HTML
    content = markdown.markdown(markdown_text)
    # Render the HTML in the template
    return render(request, 'applications/content/content_react.html', {'content': content})

applications/website/views.py
from django.shortcuts import render

def landing_page(request):
    return render(request, "website/landing_page.html")

def Example_React_App(request):
    return render(request, "applications/example_react/react_app.html")

def Example_React_Component(request):
    return render(request, "applications/example_react/react_component.html")

templates/applications/content/content_django.html
{% extends "base.html" %}

{% block meta %}
  <!-- On Page META SEO -->
  <title>{% block page_title %} Article About Python Django {% endblock %}</title>
  <meta name="description" content="{% block description %}Article About Python Django{% endblock %}">
  <meta name="keywords" content="{% block keywords %}React, JavaScript, Webpack, Django, Python, Web Development, Applications{% endblock %}">
{% endblock meta %}

{% block body %}
  {{ content|safe }}
{% endblock %}

templates/applications/content/content_react.html
{% extends "base.html" %}

{% block meta %}
  <!-- On Page META SEO -->
  <title>{% block page_title %} Article About React.js {% endblock %}</title>
  <meta name="description" content="{% block description %} Article About React.js{% endblock %}">
  <meta name="keywords" content="{% block keywords %}React, JavaScript, Webpack, Django, Python, Web Development, Applications{% endblock %}">
{% endblock meta %}

{% block body %}
  {{ content|safe }}
{% endblock %}

templates/applications/content/docs.html
{% extends "base.html" %}

{% block meta %}
  <!-- On Page META SEO -->
  <title>{% block page_title %} Django & React Docs {% endblock %}</title>
  <meta name="description" content="{% block description %}Article About Python Django{% endblock %}">
  <meta name="keywords" content="{% block keywords %}React, JavaScript, Webpack, Django, Python, Web Development, Applications{% endblock %}">
{% endblock meta %}

{% block body %}
  {{ content|safe }}
{% endblock %}

templates/applications/example_react/react_app.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
  <!-- On Page META SEO -->
  <title>{% block page_title %} Example React Application {% endblock %}</title>
  <meta name="description" content="{% block description %} Description {% endblock %}">
  <meta name="keywords" content="{% block keywords %} KeyWords {% endblock %}">
{% endblock meta %}

{% block body %}
  <div id="root" />
{% endblock %}

{% block page_js %}
  <script type="text/javascript" src="{% static 'JavaScript/bundles/FactGenerator-bundle.js' %}"></script>
{% endblock page_js %}

templates/applications/example_react/react_component.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
  <!-- On Page META SEO -->
  <title>{% block page_title %} Example Hybrid React Component {% endblock %}</title>
  <meta name="description" content="{% block description %} Description {% endblock %}">
  <meta name="keywords" content="{% block keywords %} KeyWords {% endblock %}">
{% endblock meta %}

{% block body %}
  <h2>This HTML Table is a React.js Component, the data is from the RestFul API</h2>

  <hr>

  <div id="table"></div>

  <h4>This is the hero section and illustrates how to use react components in your django templates</h4>

  {% include "website/components/hero.html" %}
  
{% endblock %}

{% block page_js %}
    <script type="text/javascript" src="{% static 'JavaScript/bundles/Table-bundle.js' %}"></script>
{% endblock page_js %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
            <!--IE compatibility-->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <!--Mobile friendly-->
        <meta name="viewport" content="width=device-width, initial-scale=1">

            <!-- On Page META SEO -->
        <title>{% block page_title %} Default SEO Title {% endblock %}</title>
        <meta name="description" content="{% block description %} Default SEO Description {% endblock %}">
        <meta name="keywords" content="{% block keywords %} Default SEO KeyWords {% endblock %}">

        {% include 'website/components/favicon.html' %}
            <!-- Styles -->
        <link rel="stylesheet" href="{% static 'Styles/style-base.css' %}">
            <!-- BootStrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
            <!-- Font Awesome Icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        
        {% block page_head %}
            <!-- <link rel="stylesheet" href="{% static '' %}"> -->
        {% endblock %}

    </head>
    <body>

        {% block body_wrapper %}

            {% block top_nav %}
                {% include 'website/components/navbar.html' %}
            {% endblock %}

            {% block messages %}
                {% include 'website/components/messages.html' %}
            {% endblock messages %}

            <div class="container">
                {% block body %}

                    <!-- PAGE -->
                    
                {% endblock body %}
            </div>

            {% block footer %}
                {% include 'website/components/footer.html' %}
            {% endblock footer %}

        {% endblock body_wrapper %}

        <script type="text/javascript" src="{% static 'JavaScript/bundles/site-bundle.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        
        {% block page_js %}
            <!-- <script type="text/javascript" src="{% static '' %}"></script> -->
        {% endblock page_js %}

    </body>
</html>

templates/website/components/favicon.html
{% load static %}
<!-- https://realfavicongenerator.net/ -->
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'images/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
<link rel="shortcut icon" href="{% static 'images/favicons/favicon.ico' %}">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-config" content="{% static 'images/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#ffffff">

templates/website/components/footer.html
{% load static %}
</br></br>
<footer style="background-color: #000000;">
    </br>
    <div class="container">
        <section>

            <div class="row">

                <div class="col text-start">
                    <span><code>GitHub</code> <a target="_blank" href="https://github.com/growth-delta"><i class="fa-brands fa-github fa-lg"></i></a></span>
                    <br><br>
                    <span><code>Media</code> <a target="_blank" href="{% url 'content:react' %}"><i class="fa-brands fa-youtube fa-lg"></i></a></span>
                    <br><br>
                    <span><a target="_blank" href="/sitemap.xml"><code>SiteMap</code> <i class="fa-solid fa-earth-africa"></i></a></span>
                </div>

                <div class="col text-end">
                    <a href="#"><img class="center" src="{% static 'images/photos/presidential_dollar.png' %}" width="90" height="90"></a>
                </div>

            </div>

            <div class="text-center">
                <small class="text-light">
                    <p>Django & React Base © Copyright <span id="copyright-year"></span></p>
                    <script>document.getElementById('copyright-year').innerText = (new Date()).getFullYear();</script>
                    <!-- Please Accredit my website in your project -->
                    <b class="text-success">Δ Django & React Configuration v0.22.22</b> | <a target="_blank" href="https://growth-delta.com/"> Growth-Delta.com</a>
                </small>
            </div>

        </section>   
    </div>
    </br>
</footer>

templates/website/components/hero.html
{% load static %}

<h1><b>Django Template Project, with a hybrid Django/React.js Frontend.</br>Developed by <a target="_blank" href="https://github.com/growth-delta">Noah Morris</a></b></h1>
</br>

<div class="row">
    <div class="col text-center">
        <div><img class="img-fluid" src="{% static 'images/branding/logo.png' %}" alt="logo" width="900px"></div>
        <h3>Noah Morris  -"If you build on top of this base django project please Accredit my website</h3><h2><a target="_blank" href="https://growth-delta.com/"> growth-delta.com</a>"</h2>
        </br></br>
    </div>
    <div class="col-md card bg-success bg-opacity-75">
        <div class="p-4">
            <h1 class="text-center text-white"><b>🐍Django⚛️React</b></h1>
            </br>
            <h4 class="hero-section" style="color:#ffd06b"><b>Build powerful web applications with ease using our Django project base template. Our template comes equipped with a fully-functional Restful API and a Webpack build pipeline that supports .jsx, .js, .ts, and .tsx files, making it easy to build modern, interactive web applications.</b></h4>
            </br>
            <b class="hero-section text-light">With our template, you can focus on building your application's unique features and functionality, while we handle the heavy lifting of setting up the infrastructure and build pipeline. Get started today and see how our Django project base template can help you build your next web application faster and more efficiently.</b>
            </br></br>
            <div class="form-floating mb-3">
                <a target="_blank" href="/static/images/graphics/homer.jpeg" class="btn btn-lg btn-warning w-100 text-white"><h3 style="font-size: 3rem;"><b>Any Key</b></h3></a>
            </div>
        </div>
    </div>
</div>

<section>
    <hr>

    <!-- You can use regular .js like this -->
    <div class="card text-center" x-data="{ count: 0 }">
    <h2 class="card-header">Alpine.js Counter Example</h2>
    <div class="row p-4">
        <button type="button" class="btn btn-lg btn-outline-dark w-50 fw-bold" x-on:click="count--">- 1</button>
        <button type="button" class="btn btn-lg btn-outline-dark w-50 fw-bold" x-on:click="count++">+ 1</button>
    </div>
    <span class="card-body fw-bolder fs-1" x-text="count"></span>
    </div>
    </br>
    <div class="container text-center w-25" x-data="{ result: '' }">
        <div class="calculator card p-4">  
            <div class="card-header">
                Alpine.js Calculator
            </div>
            <div class="card-body">
                <div class="result mb-3">
                    <input type="text" x-model="result" class="form-control" readonly>
                </div>
                <div class="row">
                    <div class="row">
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '7'">7</button>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '8'">8</button>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '9'">9</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '4'">4</button>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '5'">5</button>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '6'">6</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '1'">1</button>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '2'">2</button>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '3'">3</button>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-secondary btn-block" @click="result += '+'">+</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2">
                            <button class="btn btn-primary btn-block" @click="result += '0'">0</button>
                        </div>
                        <div class="col-2">
                        <button class="btn btn-secondary btn-block" @click="result += '.'">.</button>
                        </div>
                        <div class="col-2">
                        <button class="btn btn-secondary btn-block" @click="result += '/'">/</button>
                        </div>
                        <div class="col-2">
                        <button class="btn btn-secondary btn-block" @click="result += '-'">-</button>
                        </div>
                        </div>
                        <div class="row">
                            <div class="col-2">
                                <button class="btn btn-secondary btn-block" @click="result += '('">(</button>
                            </div>
                            <div class="col-2">
                                <button class="btn btn-secondary btn-block" @click="result += ')'">)</button>
                            </div>
                            <div class="col-2">
                                <button class="btn btn-secondary btn-block" @click="result += '*'">x</button>
                            </div>
                            <div class="col-2">
                                <button class="btn btn-success btn-block" @click="result = eval(result)">=</button>
                            </div>
                        </div>
                        <div class="col-2">
                            <button class="btn btn-warning btn-block" @click="result = ''">CLEAR</button>
                        </div>
                        <script>
                          window.addEventListener('DOMContentLoaded', () => {
                            const calculator = Alpine.data('calculator', () => ({
                              result: '0'
                            }));
                          });
                        </script>
                </div>
            </div>
        </div>
	</div>
    <hr>
</section>



<section>

    </br>
    <div class="text-center">
        <a class="btn btn-lg bg-warning bg-opacity-50 text-info" target="_blank" href="https://github.com/growth-delta/configuration"><b><i class="fa-brands fa-github fa-lg"></i> Download Code Base <i class="fa-brands fa-github fa-lg"></i></b></a>
    </div>

    </br>

    <div class="text-center">
        <a class="btn bg-success bg-opacity-75 text-warning p-4" target="_blank" href="{% url 'content:docs' %}"><b>DOCUMENTATION</b></a>
    </div>
    </br>
    
    <b>
        In the footer of your website, this project is not designed for production grade use. This is for project and portfolio application and provides 
        a decent starting point, which you can then build you unique features on. Its designed to save time for full stack developers to get moving on a 
        project in quick succession.
    </b>

    <p>
        </br>
        This is a Free base template for a Django & React application, it comes with a few simple applications and a well organized project structure.
        </br></br>
        <h2>The Project Includes</h4>
        </br>
        <b>Frontend JavaScript build pipeline</b>, which uses Webpack to bundle the JavaScript file <b>./asset/JavaScript/site.js</b> The Webpack is configured to translate; .js | .jsx and bundle them into a browser readable format in <b>./static/JavaScript/site-bundle.js</b>
        </br></br>
        <b>RestFul API</b>, which uses DRF, this helps you get your API's up and running fast. An example of creating an API from a excel file <b>./applications/api/views.py</b>
        </br></br>
        <b>MarkDown/HTML .md Content Management System</b>, This app serves .md files to your Django Templates, through the <b>./applications/content/views.py</b> this is used to create articles and content for your project.
        This is a very simplistic method for CMS but that why it's good, because you have full control over the content and delivery. Their are many floors, such as having to re-commit 
        your application in production but we suggest concentrating on the quality of your SEO content rather than quantity.
        </br></br>
        <b>Django: SEO & Sitemap</b> which uses Django to create a /sitemap.xml page, which you can register with Search Engines like GOOG, to add urls to your http://127.0.0.1:8000/sitemap.xml
        Vist <b>./applications/website/SiteMap.py</b> Meta Tags can be overridden in the templates, for an example <b>./templates/applications/content/content_django.html</b> The Default html meta tags should 
        be written in the 'django blocks' on the ./templates/base.html page this serves as the base html page for the project.
        </br></br>
        <b>Website Django Application</b> This app is for any generic webpages; terms, privacy, about etc. website templates are basically for static pages / backend rendered pages.
        </br></br>
        The idea with this is it allows you to build a your application rapidly as some of the vital infrastructure is already layed in a well structured way following good django & web practices.
        You can easily integrate react into any of your django templates give you the option to use modern JavaScript or not.
    </p>
</section>

</br>
<section>
    <div class="card text-white text-center p-3" style="background-image: url('/static/images/graphics/homer.jpeg'); background-size: cover; font-size: 4rem;">
        PRESS 'ANY KEY'|🗝️|PRESS 'ANY KEY'|🗝️
    </div>

    <!-- You can use regular .js like this -->
    <div class="text-center">
        </br>
        <a class="btn btn-lg btn-warning text-info" onclick="displayMessage()"><b>HOMER Simpson Tech Stack</b></a>
        {% block page_js %}
            <script type="text/JavaScript">
                function displayMessage() {
                    alert("Haha! I got you... The HOMER-Simpson Stack doesn't exist.\n\nLETS IMAGINE WHAT THE HOMER tech stack could be\n\nHadoop: A distributed processing system that can handle large amounts of data.\nOpenCV: An open-source computer vision library that can be used for image and video processing.\nMongoDB: A NoSQL database that can store and manage unstructured data.\nElasticsearch: A search engine that can be used to index and search large volumes of data.\nRedis: A fast in-memory data store that can be used for caching and real-time messaging.\n");
                }
            </script>
        {% endblock page_js %}
    </div>
</section>

templates/website/components/messages.html
{% load static %}
{% if messages %}
  {% for message in messages %}
    <div class="notification flex w-full justify-between alert mb-1" >
      <div>{{ message }}</div>
      <button class="delete"><i class="fa fa-times"></i></button>
    </div>
  {% endfor %}
{% endif %}
  

templates/website/components/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light sticky-top">
  <b class="container">

    <a class="navbar-brand" href="{% url 'website:landing_page' %}"><img class="img-fluid" src="{% static 'images/branding/logo.png' %}" style="height: 50px; width: auto;"></a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Content
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'content:docs' %}">Documentation</a></li>
            <li><a class="dropdown-item" href="{% url 'content:django' %}">Django</a></li>
            <li><a class="dropdown-item" href="{% url 'content:react' %}">React</a></li>
          </ul>
        </li>

        </li><li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Apps
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'website:react_app' %}">Embedded Application: Fact Generator</a></li>
            <li><a class="dropdown-item" href="{% url 'website:react_component' %}">Embedded Component: API Table</a></li>
          </ul>
        </li>

        </li><li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            API
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" target="_blank" href="{% url 'api:test_excel' %}">API: Document Links</a></li>
            <li><a class="dropdown-item" target="_blank" href="{% url 'api:test_json' %}">API: Facts</a></li>
          </ul>
        </li>

      </ul>

      <ul class="navbar-nav me-end mb-2 mb-lg-0">
        <li>
          <form id="downloadForm" method="get" action="{% static 'database/data.xlsx' %}">
            {% csrf_token %}
            <a class="btn btn-success" onclick="javascript:document.getElementById('downloadForm').submit()"><b>Do: Something? <i class="fa-solid fa-database"></i></b></a>
          </form>
        </li>
        <li><a class="nav-link"></a></li>
        <li><a class="btn btn-outline-danger text-danger"><b>Do: Nothing!</i></b></a></li>
      </ul>

    </div>
  </b>
</nav>

templates/website/landing_page.html
{% extends "base.html" %}

{% block meta %}
  <!-- On Page META SEO -->
  <title>{% block page_title %} Landing Title {% endblock %}</title>
  <meta name="description" content="{% block description %} Landing Description {% endblock %}">
  <meta name="keywords" content="{% block keywords %} Landing KeyWords {% endblock %}">
{% endblock meta %}

{% block body %}
  {% include "website/components/hero.html" %}
{% endblock %}